### ISSUE TITLE
404 bad request

### ISSUE THREAD

**Issue by GoR666LuM** [asiventsev/project2redmine#1]
Добрый день!
Столкнулся с проблемой в использовании вашей утилиты.
При запуске она выдает:
404 bad request
В проекте в MS Project создал задачу на синхронизацию, заполнил ее как написано в readme, в redmine включил restapi и jsonp. в поле ключа задачи вставил ключ пользователя. Веб-морда redmine доступна на порту 443, этот же порт указал и в теле задачи в MS Project.
Поможете в решении данной проблемы?

**Comment by asiventsev** [comment]
День добрый,
вероятнее всего, в Redmine не включен доступ по API, надо сходить в настройки и включить.

**Comment by GoR666LuM** [comment]
Все оказалось намного проще и прозаичнее: p2r не умеет работать с шифрованными соединениями и url должен быть без подкаталога.

**Comment by vavanych** [comment]
смотрите мой форк от этого проекта, прикрутил и htps, и url
