### ISSUE TITLE
 401 Unauthorized

### ISSUE THREAD

**Issue by GoR666LuM** [asiventsev/project2redmine#2]
Добрый день!
Столкнулся с вот таким поведением при синхронизации:
вывод в консоль программы:
>p2r.exe -e

Console Script for MS Project to Redmine synchronization v0.3 22/05/19 (c) A. Siventsev 2019
============================================================================================

ERROR: could not create Redmine project for some reasons
401 Unauthorized

А в логах самого redmine следующее:

Started GET "/projects/test2.json" for 10.0.1.173 at 2019-06-15 02:23:12 +0000
Processing by ProjectsController#show as JSON
  Parameters: {"id"=>"test2"}
  Current user: anonymous
Filter chain halted as :find_project rendered or redirected
Completed 404 Not Found in 10ms (ActiveRecord: 2.9ms)
Started GET "/trackers.json" for 10.0.1.173 at 2019-06-15 02:23:12 +0000
Processing by TrackersController#index as JSON
  Current user: anonymous
  Rendering trackers/index.api.rsb
  Rendered trackers/index.api.rsb (3.0ms)
Completed 200 OK in 8ms (Views: 3.4ms | ActiveRecord: 1.5ms)
Started GET "/roles/4.json" for 10.0.1.173 at 2019-06-15 02:23:12 +0000
Processing by RolesController#show as JSON
  Parameters: {"id"=>"4"}
  Current user: anonymous
  Rendering roles/show.api.rsb
  Rendered roles/show.api.rsb (0.7ms)
Completed 200 OK in 5ms (Views: 1.2ms | ActiveRecord: 1.0ms)
Started POST "/projects.json" for 10.0.1.173 at 2019-06-15 02:23:12 +0000
Processing by ProjectsController#create as JSON
  Parameters: {"project"=>{"name"=>"Проект1_03.06.19", "identifier"=>"test2", "is_public"=>false}}
  Current user: anonymous
Filter chain halted as :authorize_global rendered or redirected
Completed 401 Unauthorized in 7ms (ActiveRecord: 2.1ms)

Что нужно докрутить в настройках, чтобы программа смогла пройти авторизацию?

Немного об инсталляции:
Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.2.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  no plugin installed

**Comment by GoR666LuM** [comment]
Настройки из файла проекта:
redmine_host: 10.128.128.64
redmine_port: 80
redmine_api_key: d3843e1b577f608ce563250342e5a10bb7acb0fd
redmine_project_uuid: test2
task_default_redmine_tracker_id: 1
resource_default_redmine_role_id: 4

**Comment by asiventsev** [comment]
День добрый,

у вас в логах стоит юзер anonymous. Если заходить в API валидным ключом валидного юзера, в логах будет имя этого юзера.
Проверьте, пожалуйста, ключ.

**Comment by GoR666LuM** [comment]
Спасибо! Действительно сам дурак) пересоздал ключ и все нормально начало ходить.

P.S. Спасибо большое за утилиту! Попробуем с парнями помочь Вам с доработкой функционала, идей много) а вот программистов на ruby не одного, вроде)
